// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vertigo.Data;

#nullable disable

namespace Vertigo.Migrations
{
    [DbContext(typeof(VertigoContext))]
    [Migration("20260407160557_InitialFinal")]
    partial class InitialFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vertigo.Models.Boutique", b =>
                {
                    b.Property<int>("IDBoutique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBoutique"));

                    b.Property<string>("AdresseBoutique")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("BAN")
                        .HasColumnType("bit");

                    b.Property<int>("IdGerant")
                        .HasColumnType("int");

                    b.Property<int>("NBReport")
                        .HasColumnType("int");

                    b.Property<int>("NBvente")
                        .HasColumnType("int");

                    b.Property<string>("NomBoutique")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Registre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valide")
                        .HasColumnType("bit");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDBoutique");

                    b.HasIndex("IdGerant");

                    b.ToTable("Boutique");
                });

            modelBuilder.Entity("Vertigo.Models.Commande", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BoutiqueImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeCommande")
                        .HasColumnType("datetime2");

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Reduction")
                        .HasColumnType("bit");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PanierID");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("Vertigo.Models.Panier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IdBoutique")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PanierImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PanierPrix")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("Produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Reduction")
                        .HasColumnType("float");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IdBoutique");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("Vertigo.Models.Utilisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("BAN")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Etudiant")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NBReport")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumCarteEtu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Vertigo.Models.Boutique", b =>
                {
                    b.HasOne("Vertigo.Models.Utilisateur", "Gerant")
                        .WithMany()
                        .HasForeignKey("IdGerant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vertigo.Models.Evaluation", "Note", b1 =>
                        {
                            b1.Property<int>("BoutiqueIDBoutique")
                                .HasColumnType("int");

                            b1.Property<int>("NbNote")
                                .HasColumnType("int");

                            b1.Property<double>("Note")
                                .HasColumnType("float");

                            b1.HasKey("BoutiqueIDBoutique");

                            b1.ToTable("Boutique");

                            b1.WithOwner()
                                .HasForeignKey("BoutiqueIDBoutique");
                        });

                    b.Navigation("Gerant");

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("Vertigo.Models.Commande", b =>
                {
                    b.HasOne("Vertigo.Models.Utilisateur", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vertigo.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("PanierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("Vertigo.Models.Panier", b =>
                {
                    b.HasOne("Vertigo.Models.Boutique", "Boutique")
                        .WithMany()
                        .HasForeignKey("IdBoutique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vertigo.Models.Evaluation", "Note", b1 =>
                        {
                            b1.Property<int>("PanierID")
                                .HasColumnType("int");

                            b1.Property<int>("NbNote")
                                .HasColumnType("int");

                            b1.Property<double>("Note")
                                .HasColumnType("float");

                            b1.HasKey("PanierID");

                            b1.ToTable("Panier");

                            b1.WithOwner()
                                .HasForeignKey("PanierID");
                        });

                    b.Navigation("Boutique");

                    b.Navigation("Note")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
